const API="http://localhost:5000/api";let user=JSON.parse(localStorage.getItem("careerPilotUser")||"null"),mode="login",jobs=[],analysis=null;
const $=id=>document.getElementById(id);function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}function toast(m){$("toast").textContent=m;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2200)}
async function api(path,opt={}){let h={"Content-Type":"application/json",...(opt.headers||{})};if(user?.token)h.Authorization=`Bearer ${user.token}`;let r=await fetch(API+path,{...opt,headers:h}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||"Request failed");return d}
function show(id){["home","analyzer","jobs","dashboard"].forEach(x=>$(x).classList.toggle("hidden",x!==id));if(id==="jobs")loadJobs();if(id==="dashboard")renderDash();scrollTo(0,0)}
function authUI(){$("loginBtn").classList.toggle("hidden",!!user);$("logoutBtn").classList.toggle("hidden",!user)}
function openAuth(m="login"){mode=m;setAuth();$("authModal").classList.remove("hidden")}function setAuth(){$("authTitle").textContent=mode==="login"?"Sign in":"Create account";$("ltab").classList.toggle("active",mode==="login");$("rtab").classList.toggle("active",mode==="register");$("name").classList.toggle("hidden",mode==="login")}function closeM(id){$(id).classList.add("hidden")}
$("authForm").onsubmit=async e=>{e.preventDefault();try{let path=mode==="login"?"/auth/login":"/auth/register",b={email:$("email").value,password:$("password").value};if(mode==="register")b.name=$("name").value;let d=await api(path,{method:"POST",body:JSON.stringify(b)});user=d.user;localStorage.setItem("careerPilotUser",JSON.stringify(user));authUI();closeM("authModal");e.target.reset();toast("Welcome to CareerPilot");show("dashboard")}catch(e){toast(e.message)}}
async function analyze(){let text=$("resume").value.trim();if(!text){toast("Paste your resume first");return}try{analysis=await api("/analyze",{method:"POST",body:JSON.stringify({resumeText:text})});$("analysis").innerHTML=`<h3>Profile score</h3><div class="score">${analysis.score}/100</div><div class="progress"><i style="width:${analysis.score}%"></i></div><h4>Detected skills</h4><div class="chips">${analysis.skills.map(x=>`<span class="chip">${esc(x)}</span>`).join("")||"<span class=muted>No skills detected</span>"}</div><h4>Suggestions</h4><ul>${analysis.suggestions.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`;if(user)toast("Analysis generated")}catch(e){toast(e.message)}}
async function loadJobs(){try{jobs=await api("/jobs")}catch{jobs=[];toast("Start the backend to load jobs")}renderJobs()}
function renderJobs(){let q=$("jobSearch").value.toLowerCase(),l=$("jobLevel").value;let a=jobs.filter(j=>(!q||`${j.title} ${j.skills.join(" ")}`.toLowerCase().includes(q))&&(!l||j.level===l));$("jobGrid").innerHTML=a.length?a.map(j=>`<article class="card"><span class="eyebrow">${esc(j.level)}</span><h3>${esc(j.title)}</h3><div class="muted">${esc(j.company)} · ${esc(j.location)}</div><div class="chips">${j.skills.map(s=>`<span class="chip">${esc(s)}</span>`).join("")}</div><div class="muted">Match score: <b>${j.matchScore}%</b></div><button class="primary" onclick="saveJob('${j._id}')">Save role</button></article>`).join(""):`<div class="panel"><h3>No roles found</h3></div>`}
async function saveJob(id){if(!user){openAuth("login");return}try{await api("/saved-jobs",{method:"POST",body:JSON.stringify({jobId:id})});toast("Role saved")}catch(e){toast(e.message)}}
async function renderDash(){if(!user){$("dash").innerHTML=`<div class="panel"><h3>Sign in to save your career workspace</h3><button class="primary" onclick="openAuth()">Sign in</button></div>`;return}try{let d=await api("/dashboard");$("dash").innerHTML=`<div class="stats"><div class="stat"><span class="muted">Analyses</span><strong>${d.analyses}</strong></div><div class="stat"><span class="muted">Saved jobs</span><strong>${d.savedJobs.length}</strong></div><div class="stat"><span class="muted">Profile</span><strong>Active</strong></div></div><div class="panel"><h3>Saved roles</h3><div class="list">${d.savedJobs.map(j=>`<div class="row"><span><b>${esc(j.title)}</b><br><span class="muted">${esc(j.company)}</span></span><span class="status">${j.matchScore}% match</span></div>`).join("")||"<p>No saved roles yet.</p>"}</div></div>`}catch(e){$("dash").innerHTML=`<div class="panel"><p>${esc(e.message)}</p></div>`}}
$("logoutBtn").onclick=()=>{user=null;localStorage.removeItem("careerPilotUser");authUI();show("home");toast("Logged out")};$("jobSearch").addEventListener("input",renderJobs);$("jobLevel").addEventListener("change",renderJobs);authUI();show("home");
